### ISSUE TITLE
Doubt about the metric taken. 

### ISSUE THREAD

**Issue by as791** [bob831009/raw_image_deblurring#2]
I was going through the paper. I am having some confusion, when you report PSNR values is it in reference to original clear image or in reference to blurred input image. I think first one make sense. (Table-3)

**Comment by bob831009** [comment]
Hi @as791 
You are right! The PSNR metric is evaluated on the restored images in reference to the original shape ones.

**Comment by as791** [comment]
@bob831009  So, this is the metric has been used, PNSR=20log10(255/sqrt(mse(original, deblurred))), right?

**Comment by bob831009** [comment]
@as791 yes, the formula is correct when it is used to evaluate the difference between the sRGB images.

**Comment by as791** [comment]
@bob831009  Thank you for clearing the doubt. Closing this issue.
