### ISSUE TITLE
Questions about bits per sample, black level and white level.

### ISSUE THREAD

**Issue by leonmakise** [bob831009/raw_image_deblurring#5]
According to the dng files, it seems that black level is 2047 and white level is 16200 for those 16? or 14? bit dng files. 

Those settings are not illustrated in your paper, so I wonder how you normalize this raw data. 

Should I do like this, (im-2047.0)/(16200.0-2047.0)?

Thanks for your replies!

**Comment by bob831009** [comment]
Hi,

Thanks for your question.

To normalize by the black-level, I use the black-level value in the raw image.

So the formula is:

(Img - img.blacklevel) / (max_bit_value - img.blacklevel)

Hope this information could help you.
