### ISSUE TITLE
Questions on the image processing pipeline mentioned in Section III for an objective evaluation.

### ISSUE THREAD

**Issue by leonmakise** [bob831009/raw_image_deblurring#6]
Can you provide the same ISP pipeline to evaluate on rgb color space? 
Without your code or pertained model, I can just refer to your papers results and test my results in the same conditions for a fair comparison.

Thanks a lot.

**Comment by leonmakise** [comment]
Do you use https://github.com/AbdoKamel/simple-camera-pipeline or other codes?
If so, please provide some specific settings.

**Comment by bob831009** [comment]
Hi,

I process the raw images to sRGB images by LibRaw, an open-source library, with the default setting.

There are lots of easy-to-use Python wrappers, such as "rawpy".
https://github.com/letmaik/rawpy

Hope this information can help you.
